name: Lint

on: [push, pull_request]

jobs:

  editorconfig-checker:
    runs-on: ubuntu-latest
    container:
      image: mstruebing/editorconfig-checker:2.4.0
    steps:
      - uses: actions/checkout@v3
      - name: editorconfig-checker
        run: |
          cd ${GITHUB_WORKSPACE} && ec

  markdownlint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/igorshubovych/markdownlint-cli:v0.31.1
    steps:
      - uses: actions/checkout@v3
      - name: markdownlint
        run: |
          cd ${GITHUB_WORKSPACE} && markdownlint -r ~MD013,~MD033,~MD034

  shellcheck:
    runs-on: ubuntu-latest
    container:
      image: koalaman/shellcheck:stable
    steps:
      - uses: actions/checkout@v3
      - name: shellcheck
        run: |
          cd ${GITHUB_WORKSPACE} && shellcheck

  shfmt:
    runs-on: ubuntu-latest
    container:
      image: mvdan/shfmt:v3.5.1
    steps:
      - uses: actions/checkout@v3
      - name: shfmt
        run: |
          cd ${GITHUB_WORKSPACE} && shfmt -s -d

  yamllint:
    runs-on: ubuntu-latest
    container:
      image: sdesbure/yamllint:latest
    steps:
      - uses: actions/checkout@v3
      - name: yamllint
        run: |
          cd ${GITHUB_WORKSPACE} && yamllint -d '{extends: default, rules: {document-start: {present: false}, line-length: disable}}'
